name: CI-pr
on: 
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
      fail-fast: true
    steps:
      # By default, actions/checkout will check out the PR branch as if it was merged so that the final version can be tested
      - name: Checkout merged code to test
        uses: actions/checkout@v2.3.3
      - name: Install required version of Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Poetry
        uses: abatilo/actions-poetry@master
        with:
          poetry-version: 1.1.2
      - name: Turn off Poetry virtual environments
        run: poetry config virtualenvs.create false
      - name: Install cysystemd build dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc libsystemd-dev python3-dev
      - name: Install project dependencies
        run: poetry install
      - name: Run tests with Poetry
        run: poetry run pytest
