name: Poetry build and test
on: push
jobs:
  execute:
    name: Execute
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
      fail-fast: true
    if: ${{ !contains(github.event.head_commit.message, '!skipci') && !contains(github.event.head_commit.message, '!versionbump') }}
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2.3.3
        with:
          # Fetch the entire history
          fetch-depth: 0
      - name: Install required version of Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Poetry
        uses: abatilo/actions-poetry@master
        with:
          poetry-version: 1.1.2
      - name: Turn off Poetry virtual environments
        run: poetry config virtualenvs.create false
      - name: Install project dependencies
        run: poetry install
      - name: Run tests with Poetry
        run: poetry run pytest
      - name: Get incremented version
        uses: mathieudutour/github-tag-action@v4.6
        id: inc_version
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          # Set default to 'false' so that repo meta-commits don't create tags
          default_bump: false
          tag_prefix: v
          dry_run: true
      - name: Update version in any file that includes it
        run: OLDTAG=${{ steps.inc_version.outputs.previous_tag }}; OLDVERSION=${OLDTAG//v}; find . -type f -exec sed -i "s/$OLDVERSION/${{ steps.inc_version.outputs.new_version }}/g" '{}' ';'
