name: Poetry build and test
on: push
jobs:
  execute:
    name: Execute
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
      fail-fast: true
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2.3.3
      - name: Install required versions of Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.1.2
      - name: Set up Poetry virtual environments
        run: poetry env use python${{ matrix.python-version }}
      - name: Run tests with Poetry
        run: poetry run pytest