name: version-bump
on:
  push:
    branches: [ master ]
jobs:
  version-bump:
    runs-on: ubuntu-18.04
    if: ${{ contains(github.event.head_commit.message, '!versionbump') }}
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2.3.3
        with:
          # Fetch the entire history
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Tag version
        uses: mathieudutour/github-tag-action@v4.6
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          # Set default to 'false' so that repo meta-commits don't create tags
          default_bump: false
          tag_prefix: v
